NUMPY

In [1]:
import numpy as np

In [4]:
#creating 1D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
# creating 2D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
#using built in functions - for zero
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#using built in functions - for one
ones = np.ones((2,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#filling with specific values
values = np.full((2,3),5)
print(values)

[[5 5 5]
 [5 5 5]]


In [13]:
#identity matrix 
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#creates array from start to stop given a step
arange = np.arange(0,10,3)
print(arange)

[0 3 6 9]


In [22]:
#creates array with evenly spaced
linspace = np.linspace(0,1,5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


In [32]:
#creates random number from 0 to 1 in decimal values
random_array = np.random.rand(3,4)
print(random_array)

[[0.22730772 0.73206814 0.64148511 0.41311556]
 [0.36548176 0.33137192 0.63596077 0.32244327]
 [0.75727094 0.30114045 0.39252218 0.79316371]]


In [33]:
#creates random integer values with specifies start and end value
random_array = np.random.randint(0,20,(3,3))
print(random_array)

[[17 13  7]
 [ 8 14  9]
 [11  5 14]]


In [35]:
#array shape
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [43]:
#array dimension - speciffies 1D or 2D array
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1.ndim)

arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2.ndim)

2
3


In [48]:
#array size - gives the total number of elements
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1.size)

arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2.size)

6
12


In [49]:
#specify datatype
arr = np.array([[1,2,3],[4,5,6]])
print(arr.dtype)

int64


In [50]:
#transpose matrix
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [51]:
#seperating real values from complex numbers
arr = np.array([1+2j,3+4j])
print(arr.real)

[1. 3.]


In [52]:
#seperating imaginary values from complex numbers
arr = np.array([1+2j,3+4j])
print(arr.imag)

[2. 4.]


In [55]:
#indexing in 2D array

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])

arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

2
6


In [57]:
#indexing in multi-dimensional array

arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr[1,0,1])

#here depth 1 is [[9,10,11,12],[13,14,15,16]]

10


In [58]:
#1D array slicing
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


In [64]:
#2D array slicing
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[0:1, 0:2]) # [first_row:end_row, first_column, end_column]

[[1 2]]


In [70]:
#slice with step
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[0:2:1, 0:6:3])

[[ 1  4]
 [ 7 10]]
